name: Sync WeRead Notes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run your Node.js script
      run: WEREAD_COOKIE="${{secrets.WEREAD_COOKIE}}" NOTION_TOKEN="${{secrets.NOTION_TOKEN}}" DATABASE_ID="${{secrets.DATABASE_ID_READ}}" node ./src/scripts/weread.js

